module.exports = {
  apps: [
    {
      name: "pgvitals-collector",
      cwd: "/opt/pgvitals",
      script: "apps/collector/dist/index.js",
      node_args: "--env-file=/opt/pgvitals/.env",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
      },
      max_memory_restart: "512M",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      error_file: "/var/log/pgvitals/collector-error.log",
      out_file: "/var/log/pgvitals/collector-out.log",
      merge_logs: true,
    },
    {
      name: "pgvitals-web",
      cwd: "/opt/pgvitals/apps/web",
      script: "node_modules/next/dist/bin/next",
      args: "start -p 3000 -H 0.0.0.0",
      node_args: "--env-file=/opt/pgvitals/.env",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
        HOSTNAME: "0.0.0.0",
        NEXT_PUBLIC_CLERK_SIGN_IN_URL: "/sign-in",
        NEXT_PUBLIC_CLERK_SIGN_UP_URL: "/sign-up",
        NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: "/",
        NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: "/",
      },
      max_memory_restart: "512M",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      error_file: "/var/log/pgvitals/web-error.log",
      out_file: "/var/log/pgvitals/web-out.log",
      merge_logs: true,
    },
  ],
};
