import {
  pgTable,
  uuid,
  varchar,
  text,
  integer,
  timestamp,
  jsonb,
  primaryKey,
  index,
} from "drizzle-orm/pg-core";
import { monitoredDatabases } from "./organizations.js";

/**
 * Snapshots table — stores aggregate connection metrics per polling interval.
 * Will be converted to a TimescaleDB hypertable via migration SQL.
 *
 * Uses composite primary key (id + timestamp) because TimescaleDB requires
 * the partitioning column to be part of any unique index.
 */
export const snapshots = pgTable(
  "snapshots",
  {
    id: uuid("id").defaultRandom().notNull(),
    monitoredDbId: uuid("monitored_db_id")
      .references(() => monitoredDatabases.id, { onDelete: "cascade" })
      .notNull(),
    timestamp: timestamp("timestamp", { withTimezone: true })
      .defaultNow()
      .notNull(),
    connectionCount: integer("connection_count").notNull(),
    activeCount: integer("active_count").notNull(),
    idleCount: integer("idle_count").notNull(),
    idleInTxnCount: integer("idle_in_txn_count").notNull(),
    idleInTxnAbortedCount: integer("idle_in_txn_aborted_count")
      .default(0)
      .notNull(),
    maxConnections: integer("max_connections").notNull(),
    rawPayload: jsonb("raw_payload"),
  },
  (table) => [
    primaryKey({ columns: [table.id, table.timestamp] }),
    index("idx_snapshots_db_time").on(table.monitoredDbId, table.timestamp),
  ]
);

/**
 * Sessions snapshot table — stores per-session detail at each snapshot.
 * Will be converted to a TimescaleDB hypertable via migration SQL.
 *
 * Note: No FK to snapshots because TimescaleDB doesn't support FK references
 * to hypertables. Referential integrity is maintained at the application layer.
 */
export const sessionsSnapshot = pgTable(
  "sessions_snapshot",
  {
    id: uuid("id").defaultRandom().notNull(),
    snapshotId: uuid("snapshot_id").notNull(),
    monitoredDbId: uuid("monitored_db_id")
      .references(() => monitoredDatabases.id, { onDelete: "cascade" })
      .notNull(),
    timestamp: timestamp("timestamp", { withTimezone: true })
      .defaultNow()
      .notNull(),
    pid: integer("pid").notNull(),
    usename: varchar("usename", { length: 255 }),
    applicationName: varchar("application_name", { length: 255 }),
    clientAddr: varchar("client_addr", { length: 255 }),
    state: varchar("state", { length: 64 }),
    stateDurationSeconds: integer("state_duration_seconds"),
    queryText: text("query_text"),
    queryStart: timestamp("query_start", { withTimezone: true }),
    waitEventType: varchar("wait_event_type", { length: 64 }),
    waitEvent: varchar("wait_event", { length: 64 }),
    blockingPid: integer("blocking_pid"),
  },
  (table) => [
    primaryKey({ columns: [table.id, table.timestamp] }),
    index("idx_sessions_snapshot_db_time").on(table.monitoredDbId, table.timestamp),
  ]
);

/**
 * Root cause hints generated by the rules engine.
 * Not a hypertable — regular table with UUID primary key.
 */
export const rootCauseHints = pgTable("root_cause_hints", {
  id: uuid("id").defaultRandom().primaryKey(),
  snapshotId: uuid("snapshot_id").notNull(),
  monitoredDbId: uuid("monitored_db_id")
    .references(() => monitoredDatabases.id, { onDelete: "cascade" })
    .notNull(),
  ruleType: varchar("rule_type", { length: 128 }).notNull(),
  severity: varchar("severity", { length: 32 }).notNull(),
  title: varchar("title", { length: 512 }).notNull(),
  description: varchar("description", { length: 2048 }).notNull(),
  metadata: jsonb("metadata"),
  detectedAt: timestamp("detected_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
});
